name: App Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release --target=x86_64-unknown-linux-gnu

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ipo
          path: target/x86_64-unknown-linux-gnu/release/ipo

      - name: Release Artifacts
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/ipo
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release of ipo
