name: Rust Cross Compilation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install macOS Targets
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Build for macOS ARM
        run: cargo build --release --target=aarch64-apple-darwin
        id: macos_arm

      - name: Archive macOS ARM Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ipo-macos-arm
          path: target/aarch64-apple-darwin/release/ipo

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release of ipo

      - name: Upload macOS ARM Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/aarch64-apple-darwin/release/ipo
          asset_name: ipo-macos-arm
          asset_content_type: application/octet-stream
