on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest, arm64-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        run: rustup install stable

      - name: Build application
        run: cargo build --release --target ${{ matrix.platform }}

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set artifact path
        run: |
          artifact_path=${{ matrix.platform }}/ipo
          if [[ ${{ matrix.platform }} == "windows-latest" ]]; then
            artifact_path+=".exe"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }} release
          path: target/release/${artifact_path}
