name: Build Release Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc,aarch64-apple-darwin

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Build for macOS (ARM)
        run: cargo build --release --target aarch64-apple-darwin

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-builds
          path: |
            target/release/ipo
